language: node_js
env:
    global:
        - ENCRYPTION_LABEL: "98a7d362e1e4"
node_js:
    - stable
addons:
    browserstack:
        username: "bertrandberthelo1"
        access_key:
            secure: "qUA7fdCtg12QFxYvaSFN8czUnDqQwagvn2KFA592sIhGzIXyd9o3dmqWljjFz6BfVHDPieperbNWgXhgXDvHvBqPef9D9Sx5/UDJt05mwEZOmTbvjlIjGKXkMVy99cFifj7PUYFIK3tT++F1r5H1Jqm6kVXpThHfNhdE8PZcL2o="
before_install:
    - openssl aes-256-cbc -K $encrypted_98a7d362e1e4_key -iv $encrypted_98a7d362e1e4_iv -in travis_deploy.enc -out travis_deploy -d
    - npm install -g gulp
    - chmod 600 travis_deploy
    - eval `ssh-agent -s`
    - ssh-add travis_deploy
install:
    - npm install
script:
    - npm run build
    - npm run deploy
    - npm test
after_success:
